[package]
name = "patina"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.7.7"
pest_derive = "2.7.7"

[dependencies.inkwell]
version = "0.4.0"
features = ["llvm17-0"]
